#ifndef I_HIGH_LEVEL_CONTROLLER_HIGH_LEVEL_CONTROLLER_H
#define I_HIGH_LEVEL_CONTROLLER_HIGH_LEVEL_CONTROLLER_H

class IController
{
    
};

#endif /* I_HIGH_LEVEL_CONTROLLER_HIGH_LEVEL_CONTROLLER_H */